name: "NIployments Deployment Action"
description:
  "Push a versioned image, built from this project, to NIployments' Image Registry"

runs:
  using: "composite"
  steps:
    - name: Login to NIployments registry
      uses: docker/login-action@v1
      with:
        # These are the values of the Dev cluster.
        registry: ${{ vars.NIPLOYMENTS_REGISTRY_URL }}
        username: ${{ vars.NIPLOYMENTS_REGISTRY_USERNAME }}
        password: ${{ secrets.NIPLOYMENTS_REGISTRY_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate new tag for project image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.NIPLOYMENTS_REGISTRY_URL }}/nijobs/be
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
